// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgkbuiltistaisjebhow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impna2J1aWx0aXN0YWlzamViaG93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4OTMzNjgsImV4cCI6MjA1NzQ2OTM2OH0.PCoLIWwCB6smfiMgHargjv7qmmZUdOEV1CZOtxhn7NA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);